### ISSUE TITLE
Mac OS has no indication on the notifications section, that there's more content

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#10]
<img width="484" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/db9feb91-f308-4e23-ad07-fd32acfc1a8f">

When opening the notifications bar, I am unable to see that there's more content in the notifications section due to the max height. There are more items, but since Mac OS hides progress bars, when not used, then I cannot see it. **I only found the extra content by coincidence.**

**Comment by hofmeister** [comment]
Hi @Xayer - This has since been fixed - unfortunately we're experiencing some issues with our domain provider atm.
