### ISSUE TITLE
Once opening sample app, I am unsure what to do next

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#11]
<img width="832" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/341ad905-3682-4bb3-af14-40a2c38f7bcd">
- Once opening sample app, and all services are started,  I am unsure what to do next.

Edit: I found out some blocks were unhealthy, and showed a yellow indicator on some services, but I'm not sure what to do about it. 🤷🏻‍♂️ 

<img width="822" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/a276d8af-1ac8-43c5-ab1b-4a3f69b5ea0a">

I can see the issues in the issues tab, but I am unsure of what to do about it. 🤷🏻‍♂️ 

<img width="769" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/cb21668b-480e-4007-b423-15a830efc7f3">

I was finally able to find the "visit" button on services, but that took me a while because of https://github.com/kapetacom/kapeta-desktop/issues/12.

**Comment by mortenholm** [comment]
Hi Xavier, thanks for the feedback. We will take it into account and will look at how we can improve this going forward.
