### ISSUE TITLE
Buttons are cut off on Blocks

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#12]
<img width="189" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/906e312f-6909-407f-a8c0-aa2795ebdac6">

For some reason blocks' buttons are cut in half.

**Comment by mortenholm** [comment]
Hi Xavier, this issue should have been fixed in version version 0.37.7. Can you try again to see if it works on your side ?

**Comment by mortenholm** [comment]
Feel free to reopen if the issue persists
