### ISSUE TITLE
Clicking Visit on the User UI shows web page - but it says im not logged in

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#13]
<img width="283" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/398b0807-f86f-4ac6-b5fe-c5edc7ef5abf">

Clicking the "Visit" button, opens the webpage, but it says "not logged in" on both "change password" and "profile" tabs.

<img width="947" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/5c1b487e-5b9e-43fa-b8df-2272a06a6e09">
<img width="538" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/def8b67c-f399-4a2a-9c0f-9e8c694ba004">

**Comment by hofmeister** [comment]
Hi @Xayer and thanks for reporting. It seems you opened the User UI "fragment" directly - where you wouldn't be logged in (logging in happens elsewhere - a bit complex for a todo app for sure but to showcase the features) . The "fragments" show up in the main UI gateway block - where you can log in and where you wont see the User UI until you are.

Does that make sense? Would you consider it an improvement to not have the "globe" on fragments to avoid this sort of confusion ?

**Comment by Xayer** [comment]
That makes sense yes.

**Comment by mortenholm** [comment]
We have now made a change like Henrik described earlier. It is not possible to open the fragment directly. We have also made it easier to find the URLs which are now visible in the left side panel. We hope that it helps. Thanks for making us aware of the issue!
