### ISSUE TITLE
Edit Connection says "The following warnings were encountered when reading connection mapping"

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#14]
<img width="645" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/d8928bc8-9707-40f7-b05b-cb3610cd5077">

It says the connections were invalid and was removed, but they are still red, and my application still shows a red overlay as if my application is still broken.

<img width="556" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/6b85f499-e6ab-4d66-8321-34d5d9a7dab8">

**Comment by hofmeister** [comment]
Hi @Xayer and thanks for reporting!

A few questions to help identify where we should look. 
1. Did you change anything in the sample application before ending up with this issue or it was there when you opened it ? 
2. I see how you can misinterpret the message but what it's actually saying is that it removed the invalid ones *but* you are still missing fullfilling the interface of the client (the todo service client requires methods that the connected API does not provide)

**Comment by Xayer** [comment]
1. I did change something, in an attempt to see what would happen.
2. Alright

**Comment by hofmeister** [comment]
Ok so maybe what you changed was removing those methods from the API side?  Would it have been more helpful if you were warned when saving it that this would break the "fullfillment" or "connection" with a client ? Just trying to work out how we could better communicate the consequences of your action that led to this situation (in additition to better explaining how you resolve the situation once you're in it)

**Comment by hofmeister** [comment]
I'm closing this @Xayer - We'll look into adding some warnings when you do destructive actions that'll affect existing connections. Let us know if you need any further
