### ISSUE TITLE
Block actions hidden behind menu bar

### ISSUE THREAD

**Issue by nchrisdk** [kapetacom/kapeta-desktop#15]
The "Edit" and "Delete" action buttons are hidden behind the menu bar when I hover the postgres consumer. It doesn't appear you can scroll to reach the icons. The only way is to move the Service block, which is fine for smaller plans, but could potentially become a pain for larger plans with more blocks.

<img width="871" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1701516/d91996e6-d9be-4c08-a6c0-d27b3e5ff930">

**Comment by nchrisdk** [comment]
This is version 0.38.9 of Kapeta on Mac

**Comment by mortenholm** [comment]
Hi Christian, there should be a horizontal scrollbar and it should also be possible to zoom out. Is that not possible on your machine ?

**Comment by nchrisdk** [comment]
The controls are hidden when I hover over the provider, and no scroll bar appears. Zoom doesn't help as the service is close to the edge. 

https://github.com/kapetacom/kapeta-desktop/assets/1701516/e90c1e91-3969-4f9c-b1fe-e62ffefb90e6

**Comment by mortenholm** [comment]
Thanks! That is a bug.

**Comment by hofmeister** [comment]
Hi @nchrisdk - We've made it so you can't move blocks "out of view" in the canvas. Closing this for now
