### ISSUE TITLE
UI Improvement: When creating new block - not all fields visible, and scrollbar hidden

### ISSUE THREAD

**Issue by nwillems** [kapetacom/kapeta-desktop#16]
When at first I was creating a block, I didn't understand why I couldn't get it to complete. Then I discovered that there were more fields to fill out.

I would consider moving the required fields up, and let the icon/graphic be at the bottom.

See screenshot
<img width="690" alt="Screenshot 2023-10-22 at 22 25 06" src="https://github.com/kapetacom/kapeta-desktop/assets/172633/6650e335-dd42-4d87-8b26-a6f475cbea7c">

**Comment by hofmeister** [comment]
Thanks for reporting @nwillems - There is a fix underway where the scrollbar will be more clearly available on OSX. Will close this for now
