### ISSUE TITLE
Spinner disappears before all components are ready

### ISSUE THREAD

**Issue by sorenlouv** [kapetacom/kapeta-desktop#3]
## Observed behaviour

<img width="200" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/209966/742a8f01-28a3-4863-b064-8080870d6a41">

When starting an application, initially a loading spinner will indicate that components are starting. After a while, the spinner disappears. 

When I open a component by clicking the Globe icon I initially see the text `Error: socket hang up`. After a short while (10-20sec) the component is available.

## Expected behaviour

The spinner should not disappear until components are actually available to access.

**Comment by hofmeister** [comment]
Good point @sqren - We'll look into this.

**Comment by coderoflagos** [comment]
Hi @sqren. We have fixed the issue. You could update your Kapeta app to see the latest updates. 

I hope that helps.  👍
