### ISSUE TITLE
Logs are sometimes unavailable

### ISSUE THREAD

**Issue by sorenlouv** [kapetacom/kapeta-desktop#5]
When opening the logs, I have several times been met by a black screen. Sometimes it eventually renders the logs, other times not.

<img width="1163" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/209966/7be333b2-cc68-4963-b87f-e30d61fd7bce">

**Comment by mortenholm** [comment]
Hi @sqren, thanks for reporting this. We will look into it.

**Comment by hofmeister** [comment]
Thanks for reporting @sqren - We've made some fixed that will show why there are no logs if there are indeed no logs yet.
