### ISSUE TITLE
Inconsistencies in wording of the "todo app"

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#7]
On the website it mentions running the todo app take it for a spin.
<img width="737" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/ad6679d4-87d3-45e0-b184-bbe211c0d02b">

When running the app, it says "nodejs sample" - but there's no mention of a todo list app.
I'd assume it's the nodejs sample, but that's only because the graphics are consistent.
<img width="1106" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/2e0be031-e104-402d-90d9-3f5329b43fb4">

**Comment by mortenholm** [comment]
Hi Xavier, you are completely correct that the wording should be consistent. We will fix it.

**Comment by hofmeister** [comment]
This has since been fixed - we've actually replaced the default sample with a simpler app to make it easier to get up and running on first touch. Thanks for reporting!
