### ISSUE TITLE
Unable to click + button in the tabs

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#8]
<img width="1350" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/ae395bc4-fd0d-43c0-ac22-883b250fea4b">
I am unable to click the + button. I'd assume it does something, but it doesnt.

**Comment by mortenholm** [comment]
Thanks for reporting this issue. It has now been solved, so if you click the "+" then you will open the "My plans" tab.
