### ISSUE TITLE
UI improvement: Be able to minimise the left sidebar of the application

### ISSUE THREAD

**Issue by Xayer** [kapetacom/kapeta-desktop#9]
<img width="523" alt="image" src="https://github.com/kapetacom/kapeta-desktop/assets/1837767/88fd0c54-0769-4d13-888d-7050cb716b08">

As a user I'd like to be able to minimize the left sidebar, so that I can utilise more of the screen real estate for the application.

**Comment by mortenholm** [comment]
Thanks! This seems like a good idea and we will try to see how this fits our product. I assume you mean the white side panel since the black one already can be collapsed. @hcirbor can you take a look at the request to see if it fits the overall vision of the plan designer ?

**Comment by hcirbor** [comment]
Hi @Xayer, I agree that this could be clearer. We will add an icon to make it clear that the menu can be collapsed. We are continuously improving the UI and appreciate any feedback you may have.

**Comment by mortenholm** [comment]
Hi @Xayer, for now you can collapse the side panel by clicking the Kapeta logo. We might add a dedicated icon for it at some point. Thanks for reporting this issue.
